from suit.apps import DjangoSuitConfig
from suit.menu import ChildItem, ParentItem


class SuitConfig(DjangoSuitConfig):
    layout = 'vertical'
    menu = [
        ParentItem(
            'Заказы',
            children=[
                ChildItem(model='orders.order'),
                ChildItem(model='orders.orderfastpage'),
                ChildItem(model='orders.orderfullpage'),
                ChildItem(model='orders.thankyoupage')
            ]
        ),
        ParentItem(
            'Каталог',
            children=[
                ChildItem(model='catalog.productcategory'),
                ChildItem(model='catalog.product'),
                ChildItem(model='catalog.patterncategory'),
                ChildItem(model='catalog.patternsubcategory'),
                ChildItem(model='catalog.pattern'),
                ChildItem(model='catalog.pillow'),
                ChildItem(model='catalog.catalogpage'),
                ChildItem(model='catalog.productpage')
            ]
        ),
        ParentItem(
            'Коллекции',
            children=[
                ChildItem(model='catalog_collections.collection'),
                ChildItem(model='catalog_collections.collectionslistpage')
            ]
        ),
        ParentItem(
            'Фабрики',
            children=[
                ChildItem(model='factories.factory'),
                ChildItem(model='factories.factorylistpage')
            ]
        ),
        ParentItem(
            'Тематические зоны',
            children=[
                ChildItem(model='zones.zone'),
                ChildItem(model='zones.zoneslistpage')
            ]
        ),
        ParentItem(
            'Проекты',
            children=[
                ChildItem(model='projects.project'),
                ChildItem(model='projects.projectcategory'),
                ChildItem(model='projects.projectlistpage')
            ]
        ),
        ParentItem(
            'Страницы',
            children=[
                ChildItem(model='pages.homepage'),
                ChildItem(model='pages.flatpage'),
                ChildItem(model='pages.aboutpage'),
                ChildItem(model='pages.loginpage'),
                ChildItem(model='pages.recoverconfirmpage'),
                ChildItem(model='pages.recoverrequestpage'),
                ChildItem(model='pages.registerpage')
            ]
        ),
        ParentItem(
            'Основное',
            children=[
                ChildItem(model='core.gallery'),
                ChildItem(model='core.collectionsection'),
                ChildItem(model='core.catalogue')
            ]
        ),
        ParentItem(
            'Каталоги для скачивания',
            children=[
                ChildItem(model='download.download'),
                ChildItem(model='download.downloadrequest')
            ]
        ),
        ParentItem(
            'Пресс-центр',
            children=[
                ChildItem(model='press.news'),
                ChildItem(model='press.newslistpage'),
                ChildItem(model='press.newscategory'),
                ChildItem(model='press.articletag')
            ]
        ),
        ParentItem(
            'Контакты',
            children=[
                ChildItem(model='pages.contactspage'),
                ChildItem(model='pages.contactsoffice')
            ]
        ),
        ParentItem(
            'Документы',
            children=[
                ChildItem(model='documents.document'),
                ChildItem(model='documents.docpage'),
                ChildItem(model='documents.homepage'),
                ChildItem(model='documents.finalpage'),
                ChildItem(model='documents.delimeterpage'),
                ChildItem(model='documents.factorypage'),
                ChildItem(model='documents.textpage'),
                ChildItem(model='documents.catalogpage'),
                ChildItem(model='documents.catalogpageproduct'),
                ChildItem(model='documents.catalogpageproductpattern'),
                ChildItem(model='documents.pricepage'),
                ChildItem(model='documents.pricepageproduct'),
                ChildItem(model='documents.imagepage'),
                ChildItem(model='documents.customer'),
                ChildItem(model='documents.documentmanager'),
                ChildItem(model='documents.documentservice')
            ]
        ),
        ParentItem(
            'Пользователи',
            children=[
                ChildItem(model='users.anketa'),
                ChildItem(model='users.specialistcall'),
                ChildItem(model='users.cataloguerequest'),
                ChildItem(model='users.pricerequest'),
                ChildItem(model='users.subscribe'),
                ChildItem(model='users.user')
            ]
        ),
        ParentItem(
            'Справочники',
            children=[
                ChildItem(model='handbooks.deliverytype'),
                ChildItem(model='handbooks.filtercategory'),
                ChildItem(model='handbooks.filter'),
                ChildItem(model='handbooks.orderstatus'),
                ChildItem(model='handbooks.paymenttype'),
                ChildItem(model='handbooks.productlabel'),
                ChildItem(model='handbooks.region'),
                ChildItem(model='handbooks.selfdeliverypoint'),
                ChildItem(model='vars.actionbtn')
            ]
        ),
        ParentItem(
            'Настройки',
            children=[
                ChildItem(model='vars.menu'),
                ChildItem(model='vars.menuitem'),
                ChildItem(model='vars.siteconfig'),
                ChildItem(model='vars.teaser')
            ]
        ),
        ParentItem(
            'Формы',
            children=[
                ChildItem(model='forms.feedback'),
                ChildItem(model='forms.subscription'),
                ChildItem(model='forms.form'),
                ChildItem(model='forms.acceptedform'),
                ChildItem(model='forms.list')
            ]
        ),
        ParentItem(
            'SEO',
            children=[
                ChildItem(model='seo.robot'),
                ChildItem(model='seo.seopage'),
                ChildItem(model='seo.redirect')
            ]
        ),
        ParentItem(
            'Интеграции',
            children=[
                ChildItem(model='integrations.instagrampost'),
                ChildItem(model='integrations.moyskladlog')
            ]
        ),
        ParentItem(
            'Корзины',
            children=[
                ChildItem(model='carts.cart'),
                ChildItem(model='carts.cartpage')
            ]
        ),
        ParentItem(
            'Купоны',
            children=[
                ChildItem(model='coupons.coupon'),
                ChildItem(model='coupons.couponentry')
            ]
        ),
        ParentItem(
            'Задачи',
            children=[
                ChildItem(model='django_celery_results.taskresult')
            ]
        )
    ]
