# Generated by Django 4.0 on 2021-12-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackExchangePost',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('source_site', models.CharField(choices=[('askubuntu', 'AskUbuntu')], max_length=100, verbose_name='Сайт')),
                ('source_id', models.BigIntegerField(verbose_name='Идентификатор источника')),
                ('source_type', models.PositiveSmallIntegerField(verbose_name='Тип записи')),
                ('source_parent_id', models.BigIntegerField(verbose_name='Идентификатор источника')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Скоринг')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_cleaned', models.TextField(blank=True, null=True, verbose_name='Текст очищенный')),
                ('owner_user_id', models.BigIntegerField(verbose_name='Идентификатор автора')),
                ('source_created', models.DateTimeField(blank=True, null=True, verbose_name='Запись создана в источнике')),
                ('source_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность в источнике')),
                ('last_trained', models.DateTimeField(blank=True, null=True, verbose_name='Использована в тренировке в предыдущий раз')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('comments_count', models.IntegerField(blank=True, null=True, verbose_name='Количество комментариев')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exchange.stackexchangepost', verbose_name='Родительская запись')),
            ],
            options={
                'verbose_name': 'Запись StackExchange',
                'verbose_name_plural': 'Записи StackExchange',
            },
        ),
    ]
