# Generated by Django 4.0 on 2021-12-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stackexchangepost',
            unique_together={('source_site', 'source_id')},
        ),
    ]
