# Generated by Django 4.0 on 2021-12-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_stackexchangepost_source_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackexchangepost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exchange.stackexchangepost', verbose_name='Родительская запись'),
        ),
    ]
