# Generated by Django 4.0 on 2021-12-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_stackexchangepost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackexchangepost',
            name='owner_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор автора'),
        ),
    ]
